### PR TITLE
Changed HTTP GET to be HTTP POST

### PR DESCRIPTION
**Pull request by CoderJava**
Hi Team,
I see in your code that's you used HTTP GET for save data to Google Sheet. So, I think it's better if you used HTTP POST. Please check my code and test it.

Thanks.

### CODE REVIEW

**Comment by PatilShreyas** [comment]
Thanks for this PR @CoderJava. Looks good to me. But one thing...
Is it working? i.e. Is it giving response as expected?

**Comment by CoderJava** [comment]
Yeah sure. You can test in you Google app script and Flutter.

**Review by PatilShreyas — APPROVED** [review]
Thanks @CoderJava for this. LGTM!

**Comment by PatilShreyas** [comment]
When I run this application, I got following exception:
```
I/flutter (28945): FormatException: Unexpected character (at character 1)
I/flutter (28945): <HTML>
I/flutter (28945): ^
```
That's because of `Error 302: Temporarily Moved`.
Still, I've merged your code. I'll do more work on it.

**Comment by CoderJava** [comment]
> When I run this application, I got following exception:
> 
> ```
> I/flutter (28945): FormatException: Unexpected character (at character 1)
> I/flutter (28945): <HTML>
> I/flutter (28945): ^
> ```
> 
> That's because of `Error 302: Temporarily Moved`.
> Still, I've merged your code. I'll do more work on it.

Can you tell me how to reproduce this error? Because, I'm test it's working perfectly.

**Comment by CoderJava** [comment]
> > When I run this application, I got following exception:
> > ```
> > I/flutter (28945): FormatException: Unexpected character (at character 1)
> > I/flutter (28945): <HTML>
> > I/flutter (28945): ^
> > ```
> > 
> > 
> > That's because of `Error 302: Temporarily Moved`.
> > Still, I've merged your code. I'll do more work on it.
> 
> Can you tell me how to reproduce this error? Because, I'm test it's working perfectly.

You can test this website.
https://coderjava.github.io/Flutter2GoogleSheets-Demo/demo/web/index.html#/

That's website post data to your Google Sheet.

**Comment by PatilShreyas** [comment]
@CoderJava I tested it on Android. And that's only reason why I used GET method.

**Comment by CoderJava** [comment]
> @CoderJava I tested it on Android. And that's only reason why I used GET method.

Ok ok. I got it.

**Comment by CoderJava** [comment]
Hi,
I think the problem is from Google App Script. I found this answer from this. https://stackoverflow.com/questions/56521290/request-from-server-to-google-web-app-returns-302-code

**Pull request merged**
